In [4]:
# 1. question no. 1

In [13]:
import pandas as pd
import numpy as np

In [14]:
a=pd.read_csv('cutlets.csv')

In [15]:
a

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
import pandas as pd
import numpy as np
from scipy import stats

In [13]:
stats.ttest_rel(a["Unit A"], a["Unit B"])

Ttest_relResult(statistic=0.7536787225614314, pvalue=0.4562300768038412)

In [16]:
stats.ttest_ind(a["Unit A"], a["Unit B"])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [14]:
stats.shapiro(a["Unit A"])

(0.9649458527565002, 0.3199819028377533)

In [15]:
stats.shapiro(a["Unit B"])

(0.9727300405502319, 0.5224985480308533)

In [1]:
#2. question no. 2

In [2]:
b=pd.read_csv('LabTAT.csv')

In [3]:
b

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [4]:
b.mean()

Laboratory 1    178.361583
Laboratory 2    178.902917
Laboratory 3    199.913250
Laboratory 4    163.682750
dtype: float64

In [6]:
import scipy.stats as stats

In [9]:
stats.f_oneway(b['Laboratory 1'],b['Laboratory 2'],b['Laboratory 3'],b['Laboratory 4'])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [11]:
import scipy.stats as stats
stats.f_oneway(b.iloc[:,0], b.iloc[:,1],b.iloc[:,2],b.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [2]:
#3. question no. 3

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import scipy.stats as stats
import pylab
c=pd.read_csv('BuyerRatio.csv')

In [31]:
c

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [32]:
c1=c.drop(['Observed Values'],axis=1)


In [33]:
c1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [34]:
from scipy.stats import chi2_contingency

===Chi2 Stat===
1.595945538661058


===Degrees of Freedom===
3


===P-Value===
0.6603094907091882


===Contingency Table===
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [2]:
#question no.4

In [5]:
d=pd.read_csv('Costomer+OrderForm.csv')

In [6]:
d

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [11]:
d.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [12]:
d.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [14]:
d.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [15]:
d.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [17]:
d1=pd.DataFrame(index=['non errors','erros'],
               data={'philli':[271,29],'indo':[267,33],'malta':[269,31],'india':[280,20]})

In [18]:
d1

philli  indo  malta  india
non errors     271   267    269    280
erros           29    33     31     20

In [19]:
from scipy.stats import chi2_contingency

In [20]:
chi2_stat, p_val, dof, ex =stats.chi2_contingency(d1) 

print("Chi2 Stat")
print(chi2_stat)
print("\n")
print("Degrees of Freedom")
print(dof)
print("\n")
print("P-Value")
print(p_val)
print("\n")
print("Contingency Table")
print(ex)

Chi2 Stat
3.858960685820355


Degrees of Freedom
3


P-Value
0.2771020991233135


Contingency Table
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]
